# Generated by Django 4.2.6 on 2023-10-30 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pat_cadbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('time_of_call', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('assigned_officers', models.ManyToManyField(related_name='assigned_calls', to='pat_cadbackend.customuser')),
            ],
        ),
    ]
