# Generated by Django 4.2.6 on 2023-10-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pat_cadbackend', '0003_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
