# Generated by Django 4.2.6 on 2023-10-30 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pat_cadbackend', '0005_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcall',
            name='assigned_officers',
            field=models.ManyToManyField(related_name='assigned_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
