# Generated by Django 4.2.6 on 2023-11-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pat_cadbackend', '0006_alter_currentcall_assigned_officers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('civilians', models.ManyToManyField(related_name='warrants', to='pat_cadbackend.civilian')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('civilians', models.ManyToManyField(related_name='vehicles', to='pat_cadbackend.civilian')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('civilians', models.ManyToManyField(related_name='citations', to='pat_cadbackend.civilian')),
            ],
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_arrested', models.DateField()),
                ('civilians', models.ManyToManyField(related_name='arrests', to='pat_cadbackend.civilian')),
            ],
        ),
    ]
